export const categories = [
    "Ação",
    "Aventura",
    "RPG",
    "Estratégia",
    "Simulação",
    "Quebra-cabeça",
    "Esportes",
    "Corrida",
    "Luta",
    "Tiro",
    "Sobrevivência",
    "Horror",
    "Ficção científica",
    "Fantasia",
    "Mundo aberto",
    "Plataforma",
    "Música",
    "Educacional",
    "Casual",
    "Multijogador",
    "Jogador Único",
    "Realidade Virtual",
    "Retro",
    "Indie",
    "Visual Novel",
    "Cartas",
    "Estratégia em tempo real",
    "Turnos",
    "Hack and Slash",
    "Tower Defense",
    "Battle Royale",
    "Construção",
    "Artes marciais",
    "Zumbi",
    "Western",
    "Furtivo",
    "Mistério",
    "Histórico",
    "Cyberpunk",
    "Fotografia",
    "Espacial",
    "Vampiro",
    "Piratas",
    "Arqueologia",
    "Mágica",
    "Terrorismo",
    "Medieval",
    "Anime",
    "Futurista",
    "Policial",
    "Investigação",
    "Guerra",
    "Apocalipse",
    "Submarino",
    "Robôs",
    "Vikings",
    "Alienígenas",
    "Selva",
    "Família",
    "Comédia",
    "Romance",
    "Batalha naval",
    "Naval",
    "Ciberpunk",
    "Guerra Fria",
    "Ninja",
    "Foguetes",
    "Invasão",
    "Inferno",
    "Celestial",
    "Oeste Selvagem",
    "Hacking",
    "Tribal",
    "Governança",
    "Civilização",
    "Império",
    "Ferroviário",
    "Cinema",
    "Magia",
    "Mitologia",
    "Armas",
    "Exploração",
    "Ferrovia",
    "Voo",
    "Bicicleta",
    "Caça",
    "Física",
    "Cozinha",
    "Cultivo",
    "Natureza",
    "Transformação",
    "Distopia",
    "Comédia Negra",
    "Faroeste",
    "Investigativo",
    "Corrupção",
    "Controle",
    "Guerra Mundial",
    "Bélico",
    "Espião",
    "Detetive",
    "Estilhaçado",
    "Literatura",
    "Realismo",
    "Riqueza",
    "Investidor",
    "Política",
    "Escravidão",
    "Cavalaria",
    "Fé",
    "Apocalíptico",
    "Drama",
    "História",
    "Guerra Civil",
    "Conquista",
    "Sobrenatural",
    "Surrealismo",
    "Investimento",
    "Caverna",
    "Pandemia",
    "Inverno",
    "Verão",
    "Outono",
    "Primavera",
    "Escuridão",
    "Fantasia Científica",
    "Estratégia por Turnos",
    "Estratégia por Tempo Real",
    "Família",
    "Amigos",
  ];